### ISSUE TITLE
 Unknown provider: UserProxyProvider

### ISSUE THREAD

**Issue by kuzditomi** [martinmcwhorter/ng-ts-presentation#1]
Hi!

I found your presentation and example code online, and i'd like to make the same architecture alive myself, but when i start your code i get:
"Unknown provider: UserProxyProvider <- UserProxy <- LoginController" in browser.
Do you have any idea how to fix it? I couldn't find any reason.

Thanks,
Tamas

**Comment by martinmcwhorter** [comment]
I had a missing import in the bundle.

Add the following to src/login/index.ts:

```
 `import './UserProxy';`
```
